# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AddressName.create(degree:0 minute:0 name_part:'origin')
AddressName.create(degree:1 minute:1 name_part:'aba')
AddressName.create(degree:2 minute:2 name_part:'aca')
AddressName.create(degree:3 minute:3 name_part:'ada')
AddressName.create(degree:4 minute:4 name_part:'afa')
AddressName.create(degree:5 minute:5 name_part:'aga')
AddressName.create(degree:6 minute:6 name_part:'aha')
AddressName.create(degree:7 minute:7 name_part:'aja')
AddressName.create(degree:8 minute:8 name_part:'aka')
AddressName.create(degree:9 minute:9 name_part:'ala')
AddressName.create(degree:10 minute:10 name_part:'ama')
AddressName.create(degree:11 minute:11 name_part:'ana')
AddressName.create(degree:12 minute:12 name_part:'apa')
AddressName.create(degree:13 minute:13 name_part:'aqa')
AddressName.create(degree:14 minute:14 name_part:'ara')
AddressName.create(degree:15 minute:15 name_part:'asa')
AddressName.create(degree:16 minute:16 name_part:'ata')
AddressName.create(degree:17 minute:17 name_part:'ava')
AddressName.create(degree:18 minute:18 name_part:'awa')
AddressName.create(degree:19 minute:19 name_part:'aya')
AddressName.create(degree:20 minute:20 name_part:'aza')
AddressName.create(degree:21 minute:21 name_part:'eba')
AddressName.create(degree:22 minute:22 name_part:'eca')
AddressName.create(degree:23 minute:23 name_part:'eda')
AddressName.create(degree:24 minute:24 name_part:'efa')
AddressName.create(degree:25 minute:25 name_part:'ega')
AddressName.create(degree:26 minute:26 name_part:'eha')
AddressName.create(degree:27 minute:27 name_part:'eja')
AddressName.create(degree:28 minute:28 name_part:'eka')
AddressName.create(degree:29 minute:29 name_part:'ela')
AddressName.create(degree:30 minute:30 name_part:'ema')
AddressName.create(degree:31 minute:31 name_part:'ena')
AddressName.create(degree:32 minute:32 name_part:'epa')
AddressName.create(degree:33 minute:33 name_part:'eqa')
AddressName.create(degree:34 minute:34 name_part:'era')
AddressName.create(degree:35 minute:35 name_part:'esa')
AddressName.create(degree:36 minute:36 name_part:'eta')
AddressName.create(degree:37 minute:37 name_part:'eva')
AddressName.create(degree:38 minute:38 name_part:'ewa')
AddressName.create(degree:39 minute:39 name_part:'eya')
AddressName.create(degree:40 minute:40 name_part:'eza')
AddressName.create(degree:41 minute:41 name_part:'iba')
AddressName.create(degree:42 minute:42 name_part:'ica')
AddressName.create(degree:43 minute:43 name_part:'ida')
AddressName.create(degree:44 minute:44 name_part:'ifa')
AddressName.create(degree:45 minute:45 name_part:'iga')
AddressName.create(degree:46 minute:46 name_part:'iha')
AddressName.create(degree:47 minute:47 name_part:'ija')
AddressName.create(degree:48 minute:48 name_part:'ika')
AddressName.create(degree:49 minute:49 name_part:'ila')
AddressName.create(degree:50 minute:50 name_part:'ima')
AddressName.create(degree:51 minute:51 name_part:'ina')
AddressName.create(degree:52 minute:52 name_part:'ipa')
AddressName.create(degree:53 minute:53 name_part:'iqa')
AddressName.create(degree:54 minute:54 name_part:'ira')
AddressName.create(degree:55 minute:55 name_part:'isa')
AddressName.create(degree:56 minute:56 name_part:'ita')
AddressName.create(degree:57 minute:57 name_part:'iva')
AddressName.create(degree:58 minute:58 name_part:'iwa')
AddressName.create(degree:59 minute:59 name_part:'iya')
AddressName.create(degree:60 minute:60 name_part:'iza')
AddressName.create(degree:61 name_part:'bab')
AddressName.create(degree:62 name_part:'cab')
AddressName.create(degree:63 name_part:'dab')
AddressName.create(degree:64 name_part:'fab')
AddressName.create(degree:65 name_part:'gab')
AddressName.create(degree:66 name_part:'hab')
AddressName.create(degree:67 name_part:'jab')
AddressName.create(degree:68 name_part:'kab')
AddressName.create(degree:69 name_part:'lab')
AddressName.create(degree:70 name_part:'mab')
AddressName.create(degree:71 name_part:'nab')
AddressName.create(degree:72 name_part:'pab')
AddressName.create(degree:73 name_part:'qab')
AddressName.create(degree:74 name_part:'rab')
AddressName.create(degree:75 name_part:'sab')
AddressName.create(degree:76 name_part:'tab')
AddressName.create(degree:77 name_part:'vab')
AddressName.create(degree:78 name_part:'wab')
AddressName.create(degree:79 name_part:'yab')
AddressName.create(degree:80 name_part:'zab')
AddressName.create(degree:81 name_part:'beb')
AddressName.create(degree:82 name_part:'ceb')
AddressName.create(degree:83 name_part:'deb')
AddressName.create(degree:84 name_part:'feb')
AddressName.create(degree:85 name_part:'geb')
AddressName.create(degree:86 name_part:'heb')
AddressName.create(degree:87 name_part:'jeb')
AddressName.create(degree:88 name_part:'keb')
AddressName.create(degree:89 name_part:'leb')
AddressName.create(degree:90 name_part:'meb')
AddressName.create(degree:91 name_part:'neb')
AddressName.create(degree:92 name_part:'peb')
AddressName.create(degree:93 name_part:'qeb')
AddressName.create(degree:94 name_part:'reb')
AddressName.create(degree:95 name_part:'seb')
AddressName.create(degree:96 name_part:'teb')
AddressName.create(degree:97 name_part:'veb')
AddressName.create(degree:98 name_part:'web')
AddressName.create(degree:99 name_part:'yeb')
AddressName.create(degree:100 name_part:'zeb')
AddressName.create(degree:101 name_part:'bib')
AddressName.create(degree:102 name_part:'cib')
AddressName.create(degree:103 name_part:'dib')
AddressName.create(degree:104 name_part:'fib')
AddressName.create(degree:105 name_part:'gib')
AddressName.create(degree:106 name_part:'hib')
AddressName.create(degree:107 name_part:'jib')
AddressName.create(degree:108 name_part:'kib')
AddressName.create(degree:109 name_part:'lib')
AddressName.create(degree:110 name_part:'mib')
AddressName.create(degree:111 name_part:'nib')
AddressName.create(degree:112 name_part:'pib')
AddressName.create(degree:113 name_part:'qib')
AddressName.create(degree:114 name_part:'rib')
AddressName.create(degree:115 name_part:'sib')
AddressName.create(degree:116 name_part:'tib')
AddressName.create(degree:117 name_part:'vib')
AddressName.create(degree:118 name_part:'wib')
AddressName.create(degree:119 name_part:'yib')
AddressName.create(degree:120 name_part:'zib')
AddressName.create(degree:121 name_part:'bob')
AddressName.create(degree:122 name_part:'cob')
AddressName.create(degree:123 name_part:'dob')
AddressName.create(degree:124 name_part:'fob')
AddressName.create(degree:125 name_part:'gob')
AddressName.create(degree:126 name_part:'hob')
AddressName.create(degree:127 name_part:'job')
AddressName.create(degree:128 name_part:'kob')
AddressName.create(degree:129 name_part:'lob')
AddressName.create(degree:130 name_part:'mob')
AddressName.create(degree:131 name_part:'nob')
AddressName.create(degree:132 name_part:'pob')
AddressName.create(degree:133 name_part:'qob')
AddressName.create(degree:134 name_part:'rob')
AddressName.create(degree:135 name_part:'sob')
AddressName.create(degree:136 name_part:'tob')
AddressName.create(degree:137 name_part:'vob')
AddressName.create(degree:138 name_part:'wob')
AddressName.create(degree:139 name_part:'yob')
AddressName.create(degree:140 name_part:'zob')
AddressName.create(degree:141 name_part:'bub')
AddressName.create(degree:142 name_part:'cub')
AddressName.create(degree:143 name_part:'dub')
AddressName.create(degree:144 name_part:'fub')
AddressName.create(degree:145 name_part:'gub')
AddressName.create(degree:146 name_part:'hub')
AddressName.create(degree:147 name_part:'jub')
AddressName.create(degree:148 name_part:'kub')
AddressName.create(degree:149 name_part:'lub')
AddressName.create(degree:150 name_part:'mub')
AddressName.create(degree:151 name_part:'nub')
AddressName.create(degree:152 name_part:'pub')
AddressName.create(degree:153 name_part:'qub')
AddressName.create(degree:154 name_part:'rub')
AddressName.create(degree:155 name_part:'sub')
AddressName.create(degree:156 name_part:'tub')
AddressName.create(degree:157 name_part:'vub')
AddressName.create(degree:158 name_part:'wub')
AddressName.create(degree:159 name_part:'yub')
AddressName.create(degree:160 name_part:'zub')
AddressName.create(degree:161 name_part:'bat')
AddressName.create(degree:162 name_part:'cat')
AddressName.create(degree:163 name_part:'dat')
AddressName.create(degree:164 name_part:'fat')
AddressName.create(degree:165 name_part:'gat')
AddressName.create(degree:166 name_part:'hat')
AddressName.create(degree:167 name_part:'jat')
AddressName.create(degree:168 name_part:'kat')
AddressName.create(degree:169 name_part:'lat')
AddressName.create(degree:170 name_part:'mat')
AddressName.create(degree:171 name_part:'nat')
AddressName.create(degree:172 name_part:'pat')
AddressName.create(degree:173 name_part:'qat')
AddressName.create(degree:174 name_part:'rat')
AddressName.create(degree:175 name_part:'sat')
AddressName.create(degree:176 name_part:'tat')
AddressName.create(degree:177 name_part:'vat')
AddressName.create(degree:178 name_part:'wat')
AddressName.create(degree:179 name_part:'yat')
AddressName.create(degree:180 name_part:'zat')
AddressName.create(degree:181 name_part:'bet')
AddressName.create(degree:182 name_part:'cet')
AddressName.create(degree:183 name_part:'det')
AddressName.create(degree:184 name_part:'fet')
AddressName.create(degree:185 name_part:'get')
AddressName.create(degree:186 name_part:'het')
AddressName.create(degree:187 name_part:'jet')
AddressName.create(degree:188 name_part:'ket')
AddressName.create(degree:189 name_part:'let')
AddressName.create(degree:190 name_part:'met')
AddressName.create(degree:191 name_part:'net')
AddressName.create(degree:192 name_part:'pet')
AddressName.create(degree:193 name_part:'qet')
AddressName.create(degree:194 name_part:'ret')
AddressName.create(degree:195 name_part:'set')
AddressName.create(degree:196 name_part:'tet')
AddressName.create(degree:197 name_part:'vet')
AddressName.create(degree:198 name_part:'wet')
AddressName.create(degree:199 name_part:'yet')
AddressName.create(degree:200 name_part:'zet')
AddressName.create(degree:201 name_part:'bit')
AddressName.create(degree:202 name_part:'cit')
AddressName.create(degree:203 name_part:'dit')
AddressName.create(degree:204 name_part:'fit')
AddressName.create(degree:205 name_part:'git')
AddressName.create(degree:206 name_part:'hit')
AddressName.create(degree:207 name_part:'jit')
AddressName.create(degree:208 name_part:'kit')
AddressName.create(degree:209 name_part:'lit')
AddressName.create(degree:210 name_part:'mit')
AddressName.create(degree:211 name_part:'nit')
AddressName.create(degree:212 name_part:'pit')
AddressName.create(degree:213 name_part:'qit')
AddressName.create(degree:214 name_part:'rit')
AddressName.create(degree:215 name_part:'sit')
AddressName.create(degree:216 name_part:'tit')
AddressName.create(degree:217 name_part:'vit')
AddressName.create(degree:218 name_part:'wit')
AddressName.create(degree:219 name_part:'yit')
AddressName.create(degree:220 name_part:'zit')
AddressName.create(degree:221 name_part:'bot')
AddressName.create(degree:222 name_part:'cot')
AddressName.create(degree:223 name_part:'dot')
AddressName.create(degree:224 name_part:'fot')
AddressName.create(degree:225 name_part:'got')
AddressName.create(degree:226 name_part:'hot')
AddressName.create(degree:227 name_part:'jot')
AddressName.create(degree:228 name_part:'kot')
AddressName.create(degree:229 name_part:'lot')
AddressName.create(degree:230 name_part:'mot')
AddressName.create(degree:231 name_part:'not')
AddressName.create(degree:232 name_part:'pot')
AddressName.create(degree:233 name_part:'qot')
AddressName.create(degree:234 name_part:'rot')
AddressName.create(degree:235 name_part:'sot')
AddressName.create(degree:236 name_part:'tot')
AddressName.create(degree:237 name_part:'vot')
AddressName.create(degree:238 name_part:'wot')
AddressName.create(degree:239 name_part:'yot')
AddressName.create(degree:240 name_part:'zot')
AddressName.create(degree:241 name_part:'but')
AddressName.create(degree:242 name_part:'cut')
AddressName.create(degree:243 name_part:'dut')
AddressName.create(degree:244 name_part:'fut')
AddressName.create(degree:245 name_part:'gut')
AddressName.create(degree:246 name_part:'hut')
AddressName.create(degree:247 name_part:'jut')
AddressName.create(degree:248 name_part:'kut')
AddressName.create(degree:249 name_part:'lut')
AddressName.create(degree:250 name_part:'mut')
AddressName.create(degree:251 name_part:'nut')
AddressName.create(degree:252 name_part:'put')
AddressName.create(degree:253 name_part:'qut')
AddressName.create(degree:254 name_part:'rut')
AddressName.create(degree:255 name_part:'sut')
AddressName.create(degree:256 name_part:'tut')
AddressName.create(degree:257 name_part:'vut')
AddressName.create(degree:258 name_part:'wut')
AddressName.create(degree:259 name_part:'yut')
AddressName.create(degree:260 name_part:'zut')
AddressName.create(degree:261 name_part:'ban')
AddressName.create(degree:262 name_part:'can')
AddressName.create(degree:263 name_part:'dan')
AddressName.create(degree:264 name_part:'fan')
AddressName.create(degree:265 name_part:'gan')
AddressName.create(degree:266 name_part:'han')
AddressName.create(degree:267 name_part:'jan')
AddressName.create(degree:268 name_part:'kan')
AddressName.create(degree:269 name_part:'lan')
AddressName.create(degree:270 name_part:'man')
AddressName.create(degree:271 name_part:'nan')
AddressName.create(degree:272 name_part:'pan')
AddressName.create(degree:273 name_part:'qan')
AddressName.create(degree:274 name_part:'ran')
AddressName.create(degree:275 name_part:'san')
AddressName.create(degree:276 name_part:'tan')
AddressName.create(degree:277 name_part:'van')
AddressName.create(degree:278 name_part:'wan')
AddressName.create(degree:279 name_part:'yan')
AddressName.create(degree:280 name_part:'zan')
AddressName.create(degree:281 name_part:'ben')
AddressName.create(degree:282 name_part:'cen')
AddressName.create(degree:283 name_part:'den')
AddressName.create(degree:284 name_part:'fen')
AddressName.create(degree:285 name_part:'gen')
AddressName.create(degree:286 name_part:'hen')
AddressName.create(degree:287 name_part:'jen')
AddressName.create(degree:288 name_part:'ken')
AddressName.create(degree:289 name_part:'len')
AddressName.create(degree:290 name_part:'men')
AddressName.create(degree:291 name_part:'nen')
AddressName.create(degree:292 name_part:'pen')
AddressName.create(degree:293 name_part:'qen')
AddressName.create(degree:294 name_part:'ren')
AddressName.create(degree:295 name_part:'sen')
AddressName.create(degree:296 name_part:'ten')
AddressName.create(degree:297 name_part:'ven')
AddressName.create(degree:298 name_part:'wen')
AddressName.create(degree:299 name_part:'yen')
AddressName.create(degree:300 name_part:'zen')
AddressName.create(degree:301 name_part:'bin')
AddressName.create(degree:302 name_part:'cin')
AddressName.create(degree:303 name_part:'din')
AddressName.create(degree:304 name_part:'fin')
AddressName.create(degree:305 name_part:'gin')
AddressName.create(degree:306 name_part:'hin')
AddressName.create(degree:307 name_part:'jin')
AddressName.create(degree:308 name_part:'kin')
AddressName.create(degree:309 name_part:'lin')
AddressName.create(degree:310 name_part:'min')
AddressName.create(degree:311 name_part:'nin')
AddressName.create(degree:312 name_part:'pin')
AddressName.create(degree:313 name_part:'qin')
AddressName.create(degree:314 name_part:'rin')
AddressName.create(degree:315 name_part:'sin')
AddressName.create(degree:316 name_part:'tin')
AddressName.create(degree:317 name_part:'vin')
AddressName.create(degree:318 name_part:'win')
AddressName.create(degree:319 name_part:'yin')
AddressName.create(degree:320 name_part:'zin')
AddressName.create(degree:321 name_part:'bon')
AddressName.create(degree:322 name_part:'con')
AddressName.create(degree:323 name_part:'don')
AddressName.create(degree:324 name_part:'fon')
AddressName.create(degree:325 name_part:'gon')
AddressName.create(degree:326 name_part:'hon')
AddressName.create(degree:327 name_part:'jon')
AddressName.create(degree:328 name_part:'kon')
AddressName.create(degree:329 name_part:'lon')
AddressName.create(degree:330 name_part:'mon')
AddressName.create(degree:331 name_part:'non')
AddressName.create(degree:332 name_part:'pon')
AddressName.create(degree:333 name_part:'qon')
AddressName.create(degree:334 name_part:'ron')
AddressName.create(degree:335 name_part:'son')
AddressName.create(degree:336 name_part:'ton')
AddressName.create(degree:337 name_part:'von')
AddressName.create(degree:338 name_part:'won')
AddressName.create(degree:339 name_part:'yon')
AddressName.create(degree:340 name_part:'zon')
AddressName.create(degree:341 name_part:'bun')
AddressName.create(degree:342 name_part:'cun')
AddressName.create(degree:343 name_part:'dun')
AddressName.create(degree:344 name_part:'fun')
AddressName.create(degree:345 name_part:'gun')
AddressName.create(degree:346 name_part:'hun')
AddressName.create(degree:347 name_part:'jun')
AddressName.create(degree:348 name_part:'kun')
AddressName.create(degree:349 name_part:'lun')
AddressName.create(degree:350 name_part:'mun')
AddressName.create(degree:351 name_part:'nun')
AddressName.create(degree:352 name_part:'pun')
AddressName.create(degree:353 name_part:'qun')
AddressName.create(degree:354 name_part:'run')
AddressName.create(degree:355 name_part:'sun')
AddressName.create(degree:356 name_part:'tun')
AddressName.create(degree:357 name_part:'wun')
AddressName.create(degree:358 name_part:'vun')
AddressName.create(degree:359 name_part:'yun')
AddressName.create(degree:360 name_part:'zun')
